### ISSUE TITLE
Current out of range (overflow)

### ISSUE THREAD

**Issue by sipvoip** [e71828/pi_ina226#1]
I am seeing the correct Voltage, but I can't read the current. I am using a 500 AMP 0.00015 Ohm shunt. So the only thing I changed is Ohms from 0.002 to 0.00015. 

###
2023-05-27 11:58:31,999 - DEBUG - INA226 shunt ohms: 0.000, bus max volts: 40, shunt volts max: 0.08, max expected amps: 25.000A, VBUSCT BIT: 7, VSHSCT BIT: 7
2023-05-27 11:58:31,999 - INFO - INA226 calibrate called with: bus max volts: 40V, max shunt volts: 0.08V, max expected amps: 25.000A
2023-05-27 11:58:31,999 - INFO - INA226 max possible current: 546.13A
2023-05-27 11:58:31,999 - INFO - INA226 max expected current: 25.000A
2023-05-27 11:58:32,000 - INFO - INA226 expected current LSB base on max_expected_amps: 7.629e-04 A/bit
2023-05-27 11:58:32,000 - INFO - INA226 current_lsb is less equal than min_device_current_lsb, use the latter
2023-05-27 11:58:32,000 - INFO - INA226 current LSB: 1.042e-03 A/bit
2023-05-27 11:58:32,000 - INFO - INA226 power LSB: 2.625e-02 W/bit
2023-05-27 11:58:32,000 - INFO - INA226 max current before overflow: 34.1333A
2023-05-27 11:58:32,000 - INFO - INA226 max shunt voltage before overflow: 5.1200mV
2023-05-27 11:58:32,000 - INFO - INA226 calibration: 0x7fff (32767)
2023-05-27 11:58:32,000 - DEBUG - INA226 calibration: 0x7fff
2023-05-27 11:58:32,001 - DEBUG - INA226 write register 0x05: 0x7fff 0b0111111111111111
2023-05-27 11:58:32,001 - DEBUG - INA226 configuration: 0x41ff
2023-05-27 11:58:32,001 - DEBUG - INA226 write register 0x00: 0x41ff 0b0100000111111111
2023-05-27 11:58:32,002 - DEBUG - INA226 limit value: 0x0fa0
2023-05-27 11:58:32,002 - DEBUG - INA226 write register 0x07: 0x0fa0 0b0000111110100000
2023-05-27 11:58:32,003 - DEBUG - INA226 mask/enable: 0x1003
2023-05-27 11:58:32,003 - DEBUG - INA226 write register 0x06: 0x1003 0b0001000000000011
===================================================Begin to read
2023-05-27 11:58:35,007 - DEBUG - INA226 read register 0x02: 0x2640 0b0010011001000000
Bus Voltage    : 12.240 V
2023-05-27 11:58:35,008 - DEBUG - INA226 read register 0x06: 0x100f 0b0001000000001111
Traceback (most recent call last):
  File "/home/nathan/pi_ina226/example.py", line 21, in <module>
    read()
  File "/home/nathan/pi_ina226/example.py", line 9, in read
    print("Bus Current    : %.3f mA" % ina.current())
  File "/home/nathan/pi_ina226/ina226.py", line 177, in current
    self._handle_current_overflow()
  File "/home/nathan/pi_ina226/ina226.py", line 299, in _handle_current_overflow
    raise DeviceRangeError(self.__GAIN_VOLTS)
ina226.DeviceRangeError: Current out of range (overflow), for gain 0.08V

**Comment by e71828** [comment]
change `max_expected_amps`  to `None`.

when : Maximum Expected Current = 25 A,
Current_LSB=25/2**15 =  0.7629  mA; 
Current_LSB seems a liitle small for your occassion with a samll `R_shunt(0.15 mOh)`.

**Comment by e71828** [comment]
> 2023-05-27 11:58:32,000 - INFO - INA226 max current before overflow: 34.1333A
> 2023-05-27 11:58:32,000 - INFO - INA226 max shunt voltage before overflow: 5.1200mV

Please check the value of shunt voltage, because the 1 LSB step size for Shunt voltage equals to 2.5 uV, **fixed value**.

### Comment out the two lines for possible values, this will get the shunt voltage and current ignoring the error.

https://github.com/e71828/pi_ina226/blob/ccbaa21c1439f0c9728ef838162f4a18638e21dc/ina226.py#L177
https://github.com/e71828/pi_ina226/blob/ccbaa21c1439f0c9728ef838162f4a18638e21dc/ina226.py#L193


Register: Current = ShuntVoltage * Calibration / 2048
In your condition, Current = ShuntVoltage * 16, it is easier for overlflow.
Maybe you can divide `__CALIBRATION_FACTOR` by 15

**Comment by sipvoip** [comment]
Thanks for your help.

I divided by 15.

    #__CALIBRATION_FACTOR = 0.00512
    __CALIBRATION_FACTOR = 0.003413

And commented out the overflows:

python example.py 
2023-05-29 10:01:55,081 - DEBUG - INA226 shunt ohms: 0.000, bus max volts: 40, shunt volts max: 0.08, max expected amps: 25.000A, VBUSCT BIT: 7, VSHSCT BIT: 7
2023-05-29 10:01:55,082 - INFO - INA226 calibrate called with: bus max volts: 40V, max shunt volts: 0.08V, max expected amps: 25.000A
2023-05-29 10:01:55,082 - INFO - INA226 max possible current: 546.13A
2023-05-29 10:01:55,082 - INFO - INA226 max expected current: 25.000A
2023-05-29 10:01:55,082 - INFO - INA226 expected current LSB base on max_expected_amps: 8.194e-03 A/bit
2023-05-29 10:01:55,082 - INFO - INA226 current LSB: 8.194e-03 A/bit
2023-05-29 10:01:55,082 - INFO - INA226 power LSB: 2.065e-01 W/bit
2023-05-29 10:01:55,082 - INFO - INA226 max current before overflow: 268.4939A
2023-05-29 10:01:55,082 - INFO - INA226 max shunt voltage before overflow: 40.2741mV
2023-05-29 10:01:55,083 - INFO - INA226 calibration: 0x0ad8 (2776)
2023-05-29 10:01:55,083 - DEBUG - INA226 calibration: 0x0ad8
2023-05-29 10:01:55,083 - DEBUG - INA226 write register 0x05: 0x0ad8 0b0000101011011000
2023-05-29 10:01:55,083 - DEBUG - INA226 configuration: 0x41ff
2023-05-29 10:01:55,084 - DEBUG - INA226 write register 0x00: 0x41ff 0b0100000111111111
2023-05-29 10:01:55,084 - DEBUG - INA226 limit value: 0x0fa0
2023-05-29 10:01:55,084 - DEBUG - INA226 write register 0x07: 0x0fa0 0b0000111110100000
2023-05-29 10:01:55,085 - DEBUG - INA226 mask/enable: 0x1003
2023-05-29 10:01:55,085 - DEBUG - INA226 write register 0x06: 0x1003 0b0001000000000011
===================================================Begin to read
2023-05-29 10:01:58,089 - DEBUG - INA226 read register 0x02: 0x2639 0b0010011000111001
Bus Voltage    : 12.231 V
2023-05-29 10:01:58,090 - DEBUG - INA226 read register 0x04: 0x-8000 0bb1000000000000000
Bus Current    : -268502.130 mA
2023-05-29 10:01:58,091 - DEBUG - INA226 read register 0x02: 0x2639 0b0010011000111001
2023-05-29 10:01:58,092 - DEBUG - INA226 read register 0x01: 0x-8000 0bb1000000000000000
Supply Voltage : 12.149 V
2023-05-29 10:01:58,092 - DEBUG - INA226 read register 0x01: 0x-8000 0bb1000000000000000
Shunt voltage  : -81.920 mV
2023-05-29 10:01:58,093 - DEBUG - INA226 read register 0x06: 0x100f 0b0001000000001111
Traceback (most recent call last):
  File "/home/nathan/pi_ina226/example.py", line 21, in <module>
    read()
  File "/home/nathan/pi_ina226/example.py", line 12, in read
    print("Power          : %.3f mW" % ina.power())
  File "/home/nathan/pi_ina226/ina226.py", line 187, in power
    self._handle_current_overflow()
  File "/home/nathan/pi_ina226/ina226.py", line 301, in _handle_current_overflow
    raise DeviceRangeError(self.__GAIN_VOLTS)
ina226.DeviceRangeError: Current out of range (overflow), for gain 0.08V


I am using a 500A 75mv 0.00015 Ohm shunt, How do I get the max expected to be 500 Amps? Thanks for your help, if you email me at nathan at robotics dot net your Paypal I can send you some $$ for your help.

**Comment by e71828** [comment]
This problem seems hard to be solved, the shunt voltage reaches the maximum value( 81.920 mV ), but the register can only record number less than 32767.

500 A current drifts badly and is easily overloaded.
Maybe the shunt is not enough(overflow with 81.92 mV). You could try a shunt with less than 0.00015 ohms.

**Comment by sipvoip** [comment]
I guess the issue was a bad chip, this was my first time working with SMT this small, I tried a new chip and it works perfectly.

**Comment by hamzah0** [comment]
@sipvoip Hi how did you connect the INA226 and the Raspberry pi? Could you send a picture of it. I know there is a photo in the repository but I cant actually understand. So Could you please help me?
